language: python
python:
    - "3.4"
install: "pip install -r requirements-test.txt"
before_script:
    - "cp micall/settings_default.py micall/settings.py"
script: "coverage run --source=micall/core,micall/g2p,micall/hivdb,micall/monitor -m unittest discover"

after_success:
    - pip install codecov
    - codecov
