language: python
python:
    - "3.8"
before_install:
  - mkdir -p ~/bin
  - export PATH=$PATH:~/bin
  # Singularity
  - sudo apt-get install -qq python dh-autoreconf build-essential libarchive-dev squashfs-tools
  - git clone https://github.com/singularityware/singularity.git
  - cd singularity
  - git checkout -q tags/2.5.2
  - ./autogen.sh
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  - cd ..
  - rm -rf singularity
  # IVA assembler:
  - sudo apt-get install -y zlib1g-dev libncurses5-dev libncursesw5-dev mummer samtools ncbi-blast+
  - pushd ~/bin
  - wget -q http://sun.aei.polsl.pl/kmc/download-2.1.1/linux/kmc
  - wget -q http://sun.aei.polsl.pl/kmc/download-2.1.1/linux/kmc_dump
  - chmod +x kmc kmc_dump
  - cd ~
  - wget -q http://downloads.sourceforge.net/project/smalt/smalt-0.7.6-bin.tar.gz
  - tar -xzf smalt-0.7.6-bin.tar.gz
  - ln -s ~/smalt-0.7.6-bin/smalt_x86_64 ~/bin/smalt
  # Rust and merge-mates
  - sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
  - cargo install --root ~/ --git https://github.com/jeff-k/merge-mates.git
  - popd

install: "pip install -r requirements-test.txt"
script:
  - coverage run --source=micall/core,micall/g2p,micall/resistance,micall/monitor -m pytest || travis_terminate 1
  - echo 'singularity build' && echo -en 'travis_fold:start:singularity\\r'
  - sudo singularity build micall.simg Singularity || travis_terminate 1
  - echo -en 'travis_fold:end:singularity\\r'
  - python release_test_microtest.py micall.simg

after_success:
  - pip list
  - rm -rf micall/tests/microtest/scratch
  - pip install codecov
  - codecov
