language: python
python:
    - "3.4"
install: "pip install coverage python-Levenshtein matplotlib requests reportlab pyyaml cutadapt==1.11"
script: "coverage run -m unittest discover -p '*_test.py'"

after_success:
    - pip install codecov
    - codecov