language: python
python:
    - "3.4"
sudo: required
before_install:
    - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
install: "pip install python-Levenshtein matplotlib requests reportlab pyyaml cutadapt==1.11"
script: "coverage run -m unittest discover -p '*_test.py'"

after_success:
    - pip install codecov
    - codecov