language: python
python:
    - "3.6"
install: "pip install -r requirements-test.txt"
script: "coverage run --source=micall/core,micall/g2p,micall/resistance,micall/monitor -m pytest"

after_success:
    - pip install codecov
    - codecov
