language: python
python:
    - "3.4"
install: "pip install coverage python-Levenshtein matplotlib requests reportlab pyyaml cutadapt==1.11"
before_script:
    - "cp micall/settings_default.py micall/settings.py"
    - "cd micall/alignment/ && python setup.py install && cd ../.."
script: "coverage run --source=micall/core,micall/g2p,micall/hivdb,micall/monitor -m unittest discover"

after_success:
    - pip install codecov
    - codecov