#!/usr/bin/env python3
"""
Helper script to update HIVdb version in MiCall.

This script automates the tedious parts of updating the HIVdb version after
you've downloaded the new XML file from Stanford.

Usage:
    python update_hivdb.py <xml_file> <version> <modification_date>

Example:
    python update_hivdb.py HIVDB_9.8.xml 9.8 "2024-01-15"

The script will:
1. Copy the XML file to the correct location
2. Update resistance.py with the new path
3. Update genreport.yaml with the new version and date
4. Print next steps for test updates
"""

import re
import sys
from pathlib import Path


def update_resistance_py(version):
    """Update the HIV_RULES_PATH in resistance.py."""
    resistance_file = Path("micall/resistance/resistance.py")

    if not resistance_file.exists():
        print(f"Error: {resistance_file} not found!")
        return False

    content = resistance_file.read_text()

    # Update the HIV_RULES_PATH line
    old_pattern = r"HIV_RULES_PATH = os\.path\.join\(os\.path\.dirname\(__file__\), 'HIVDB_[\d.]+\.xml'\)"
    new_line = f"HIV_RULES_PATH = os.path.join(os.path.dirname(__file__), 'HIVDB_{version}.xml')"

    new_content = re.sub(old_pattern, new_line, content)

    if new_content == content:
        print(f"Warning: Could not find HIV_RULES_PATH pattern in {resistance_file}")
        return False

    resistance_file.write_text(new_content)
    print(f"✓ Updated {resistance_file}")
    return True


def update_genreport_yaml(version, mod_date):
    """Update the version and date in genreport.yaml."""
    genreport_file = Path("micall/resistance/genreport.yaml")

    if not genreport_file.exists():
        print(f"Error: {genreport_file} not found!")
        return False

    content = genreport_file.read_text()

    # Update the generated_by_text line for HIV
    old_pattern = r"(Generated by MiCall \{\} on Illumina BaseSpace using Stanford HIVdb\s+)[\d.]+,\s*modified on\s+[\d-]+"
    new_text = f"\\g<1>{version}, modified on {mod_date}"

    new_content = re.sub(old_pattern, new_text, content)

    if new_content == content:
        print(f"Warning: Could not find version pattern in {genreport_file}")
        print("You may need to update this file manually.")
        return False

    genreport_file.write_text(new_content)
    print(f"✓ Updated {genreport_file}")
    return True


def copy_xml_file(xml_file, version):
    """Copy the XML file to the correct location."""
    xml_path = Path(xml_file)

    if not xml_path.exists():
        print(f"Error: {xml_file} not found!")
        return False

    dest_dir = Path("micall/resistance")
    dest_file = dest_dir / f"HIVDB_{version}.xml"

    if dest_file.exists():
        response = input(f"{dest_file} already exists. Overwrite? (y/n): ")
        if response.lower() != "y":
            print("Aborted.")
            return False

    import shutil

    shutil.copy(xml_path, dest_file)
    print(f"✓ Copied {xml_file} to {dest_file}")
    return True


def print_next_steps(version):
    """Print next steps for the user."""
    print("\n" + "=" * 70)
    print("NEXT STEPS:")
    print("=" * 70)
    print("\n1. Review the changes:")
    print("   git status")
    print("   git diff micall/resistance/resistance.py")
    print("   git diff micall/resistance/genreport.yaml")

    print("\n2. Check if new drugs were added in HIVdb {version}:")
    print("   - Open the XML file and search for <DRUG>")
    print("   - If new drugs exist, add them to genreport.yaml")
    print("     in the appropriate drug class section")

    print("\n3. Update test files:")
    print("   - micall/tests/test_resistance.py")
    print("     Update any version number assertions")
    print("   - micall/tests/test_asi_algorithm.py")
    print("     Update expected resistance scores if needed")

    print("\n4. Run tests:")
    print("   pytest micall/tests/test_resistance.py")
    print("   pytest micall/tests/test_asi_algorithm.py")
    print("   pytest  # Run all tests")

    print("\n5. If tests fail due to algorithm changes:")
    print("   - Check HIVdb release notes")
    print("   - Verify changes are expected")
    print("   - Update test expectations accordingly")

    print("\n6. Delete old HIVDB XML files if present:")
    print("   rm micall/resistance/HIVDB_9.4.xml  # if not already deleted")

    print("\n7. Commit and create PR:")
    print("   git add .")
    print(f"   git commit -m 'Update HIVdb to version {version}'")
    print("   git push origin <your-branch>")
    print("   # Then create a PR on GitHub referencing issue #1407")
    print("\n" + "=" * 70)


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)

    xml_file = sys.argv[1]
    version = sys.argv[2]
    mod_date = sys.argv[3]

    # Validate inputs
    if not re.match(r"^\d+\.\d+$", version):
        print(f"Error: Version '{version}' should be in format X.X (e.g., 9.8)")
        sys.exit(1)

    if not re.match(r"^\d{4}-\d{2}-\d{2}$", mod_date):
        print(f"Error: Date '{mod_date}' should be in format YYYY-MM-DD")
        sys.exit(1)

    print(f"Updating HIVdb to version {version} (modified {mod_date})")
    print("-" * 70)

    # Check we're in the right directory
    if not Path("micall/resistance").exists():
        print("Error: Please run this script from the MiCall root directory")
        sys.exit(1)

    success = True

    # Copy XML file
    if not copy_xml_file(xml_file, version):
        success = False

    # Update Python file
    if not update_resistance_py(version):
        success = False

    # Update YAML file
    if not update_genreport_yaml(version, mod_date):
        success = False

    if success:
        print("\n✓ All updates completed successfully!")
        print_next_steps(version)
    else:
        print("\n⚠ Some updates failed. Please check the errors above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
